package com.londonappbrewery.magiceightball;

import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.view.View;
import android.widget.Button;
import android.widget.ImageView;

import java.util.Random;

public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        //get a reference for the ball image view into an image view variable
        final ImageView ballDisplay = (ImageView) findViewById(R.id.image_eightBall);

        //create array to hold all ball images
        final int[] ballArray = {R.drawable.ball1,
                R.drawable.ball2,
                R.drawable.ball3,
                R.drawable.ball4,
                R.drawable.ball5};

        //get a reference for the button "Ask" in a button variable
        Button myButton = (Button) findViewById(R.id.askButton);

        //set onClick listener for the Ask button
        myButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                //create a Random object to generate a random number
                Random randomNumberGenerator = new Random();

                //generate and store random number in a int variable
                int number = randomNumberGenerator.nextInt(5);

                /*set an image on the eight ball image view based from the array based on the random
                /index generated by the Random object*/
                ballDisplay.setImageResource(ballArray[number]);
            }
        });


    }
}
